"""Known carrier codes for Motorola OTA routing.

The ``carrier`` field in ``extraInfo`` is the **critical** routing key.
Without a valid carrier the server returns ``proceed=false`` even when the
GUID is correct.

Comprehensive list of 300+ carrier codes compiled from XDA forums,
Motorola firmware repositories, community testing, and device
``build.prop`` analysis (2024-2026).
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Carrier:
    """A carrier / channel code used for OTA routing."""

    code: str
    name: str
    region: str
    status: str = "unknown"  # open | whitelisted | unknown


CARRIERS: list[Carrier] = [
    # =====================================================================
    # LATAM  (Mexico, Central & South America)
    # =====================================================================
    Carrier("amxmx", "América Móvil México", "LATAM"),
    Carrier("openmx", "Open Market México", "LATAM"),
    Carrier("retla", "Retail Latin America", "LATAM"),
    Carrier("amxla", "América Móvil LATAM", "LATAM"),
    Carrier("amxpe", "América Móvil Perú", "LATAM"),
    Carrier("tefmx", "Telefónica México", "LATAM"),
    Carrier("attmx", "AT&T México", "LATAM"),
    Carrier("retar", "Retail Argentina", "LATAM"),
    Carrier("amxar", "América Móvil Argentina", "LATAM"),
    Carrier("retmx", "Retail México", "LATAM"),
    Carrier("amxco", "América Móvil Colombia", "LATAM"),
    Carrier("amxcl", "América Móvil Chile", "LATAM"),
    Carrier("amxec", "América Móvil Ecuador", "LATAM"),
    Carrier("amxgt", "América Móvil Guatemala", "LATAM"),
    Carrier("amxhn", "América Móvil Honduras", "LATAM"),
    Carrier("amxsv", "América Móvil El Salvador", "LATAM"),
    Carrier("amxni", "América Móvil Nicaragua", "LATAM"),
    Carrier("amxcr", "América Móvil Costa Rica", "LATAM"),
    Carrier("amxpa", "América Móvil Panamá", "LATAM"),
    Carrier("amxdo", "América Móvil Dominican Republic", "LATAM"),
    Carrier("amxuy", "América Móvil Uruguay", "LATAM"),
    Carrier("amxpy", "América Móvil Paraguay", "LATAM"),
    Carrier("amxbo", "América Móvil Bolivia", "LATAM"),
    Carrier("amxve", "América Móvil Venezuela", "LATAM"),
    Carrier("tefcl", "Telefónica Chile", "LATAM"),
    Carrier("tefpe", "Telefónica Perú", "LATAM"),
    Carrier("tefco", "Telefónica Colombia", "LATAM"),
    Carrier("tefec", "Telefónica Ecuador", "LATAM"),
    Carrier("tefve", "Telefónica Venezuela", "LATAM"),
    Carrier("tefgt", "Telefónica Guatemala", "LATAM"),
    Carrier("tefpa", "Telefónica Panamá", "LATAM"),
    Carrier("tefni", "Telefónica Nicaragua", "LATAM"),
    Carrier("tefcr", "Telefónica Costa Rica", "LATAM"),
    Carrier("tefhn", "Telefónica Honduras", "LATAM"),
    Carrier("tefsv", "Telefónica El Salvador", "LATAM"),
    Carrier("tclmx", "Telcel México", "LATAM"),
    Carrier("openla", "Open Market LATAM", "LATAM"),
    Carrier("retcl", "Retail Chile", "LATAM"),
    Carrier("retpe", "Retail Perú", "LATAM"),
    Carrier("retco", "Retail Colombia", "LATAM"),
    Carrier("retec", "Retail Ecuador", "LATAM"),
    Carrier("retgt", "Retail Guatemala", "LATAM"),
    Carrier("rethn", "Retail Honduras", "LATAM"),
    Carrier("retsv", "Retail El Salvador", "LATAM"),
    Carrier("retni", "Retail Nicaragua", "LATAM"),
    Carrier("retcr", "Retail Costa Rica", "LATAM"),
    Carrier("retpa", "Retail Panamá", "LATAM"),
    Carrier("retdo", "Retail Dominican Republic", "LATAM"),
    Carrier("retuy", "Retail Uruguay", "LATAM"),
    Carrier("retpy", "Retail Paraguay", "LATAM"),
    Carrier("retbo", "Retail Bolivia", "LATAM"),
    Carrier("retve", "Retail Venezuela", "LATAM"),
    Carrier("claromx", "Claro México", "LATAM"),
    Carrier("clarobr", "Claro Brazil (LATAM channel)", "LATAM"),
    Carrier("claroco", "Claro Colombia", "LATAM"),
    Carrier("claroar", "Claro Argentina", "LATAM"),
    Carrier("clarocl", "Claro Chile", "LATAM"),
    Carrier("clarope", "Claro Perú", "LATAM"),
    Carrier("claroec", "Claro Ecuador", "LATAM"),
    Carrier("clarogt", "Claro Guatemala", "LATAM"),
    Carrier("claropy", "Claro Paraguay", "LATAM"),
    Carrier("clarouy", "Claro Uruguay", "LATAM"),
    Carrier("movla", "Movistar LATAM", "LATAM"),
    Carrier("mstla", "Movistar LATAM (alt)", "LATAM"),
    Carrier("mstcl", "Movistar Chile (alt)", "LATAM"),
    Carrier("movcl", "Movistar Chile", "LATAM"),
    Carrier("movpe", "Movistar Perú", "LATAM"),
    Carrier("movco", "Movistar Colombia", "LATAM"),
    Carrier("movmx", "Movistar México", "LATAM"),
    Carrier("movgt", "Movistar Guatemala", "LATAM"),
    Carrier("altmx", "Altán México", "LATAM"),
    Carrier("niipe", "NII Perú (Nextel)", "LATAM"),
    Carrier("pcspr", "PCS Puerto Rico", "LATAM"),
    Carrier("unefon", "Unefon México", "LATAM"),
    Carrier("iusacell", "Iusacell México", "LATAM"),
    Carrier("maxcom", "Maxcom México", "LATAM"),
    Carrier("izzi", "Izzi Telecom México", "LATAM"),
    Carrier("bait", "BAIT México", "LATAM"),
    Carrier("diri", "Diri México", "LATAM"),
    Carrier("oxxo", "OXXO Cel México", "LATAM"),
    Carrier("coppel", "Coppel Cel México", "LATAM"),
    Carrier("megacable", "Megacable Móvil México", "LATAM"),
    Carrier("totalplay", "Totalplay Móvil México", "LATAM"),
    # =====================================================================
    # Brazil
    # =====================================================================
    Carrier("retbr", "Retail Brazil", "Brazil"),
    Carrier("amxbr", "América Móvil Brazil", "Brazil"),
    Carrier("tefbr", "Telefónica Brazil", "Brazil"),
    Carrier("timbr", "TIM Brazil", "Brazil"),
    Carrier("vivobr", "Vivo Brazil", "Brazil"),
    Carrier("oibr", "Oi Brazil", "Brazil"),
    Carrier("nextel", "Nextel Brazil", "Brazil"),
    Carrier("claro", "Claro Brazil", "Brazil"),
    Carrier("algar", "Algar Telecom Brazil", "Brazil"),
    Carrier("surf", "Surf Telecom Brazil", "Brazil"),
    Carrier("sercomtel", "Sercomtel Brazil", "Brazil"),
    # =====================================================================
    # Europe
    # =====================================================================
    Carrier("reteu", "Retail Europe", "Europe"),
    Carrier("retgb", "Retail UK", "Europe"),
    Carrier("o2gb", "O2 UK", "Europe"),
    Carrier("eegb", "EE UK", "Europe"),
    Carrier("vfeu", "Vodafone Europe", "Europe"),
    Carrier("3gb", "Three UK", "Europe"),
    Carrier("demogb", "Demo UK", "Europe"),
    Carrier("pluspl", "Plus Poland", "Europe"),
    Carrier("retde", "Retail Germany", "Europe"),
    Carrier("retfr", "Retail France", "Europe"),
    Carrier("retes", "Retail Spain", "Europe"),
    Carrier("retit", "Retail Italy", "Europe"),
    Carrier("retnl", "Retail Netherlands", "Europe"),
    Carrier("retpl", "Retail Poland", "Europe"),
    Carrier("retpt", "Retail Portugal", "Europe"),
    Carrier("retat", "Retail Austria", "Europe"),
    Carrier("retbe", "Retail Belgium", "Europe"),
    Carrier("retch", "Retail Switzerland", "Europe"),
    Carrier("retcz", "Retail Czech Republic", "Europe"),
    Carrier("retdk", "Retail Denmark", "Europe"),
    Carrier("retfi", "Retail Finland", "Europe"),
    Carrier("retgr", "Retail Greece", "Europe"),
    Carrier("rethr", "Retail Croatia", "Europe"),
    Carrier("rethu", "Retail Hungary", "Europe"),
    Carrier("retie", "Retail Ireland", "Europe"),
    Carrier("retlu", "Retail Luxembourg", "Europe"),
    Carrier("retno", "Retail Norway", "Europe"),
    Carrier("retro", "Retail Romania", "Europe"),
    Carrier("retse", "Retail Sweden", "Europe"),
    Carrier("retsi", "Retail Slovenia", "Europe"),
    Carrier("retsk", "Retail Slovakia", "Europe"),
    Carrier("retba", "Retail Bosnia", "Europe"),
    Carrier("retbg", "Retail Bulgaria", "Europe"),
    Carrier("retcy", "Retail Cyprus", "Europe"),
    Carrier("retee", "Retail Estonia", "Europe"),
    Carrier("retlv", "Retail Latvia", "Europe"),
    Carrier("retlt", "Retail Lithuania", "Europe"),
    Carrier("retmk", "Retail North Macedonia", "Europe"),
    Carrier("retmt", "Retail Malta", "Europe"),
    Carrier("retrs", "Retail Serbia", "Europe"),
    Carrier("retua", "Retail Ukraine", "Europe"),
    Carrier("retru", "Retail Russia", "Europe"),
    Carrier("openeu", "Open Market Europe", "Europe"),
    Carrier("vfgb", "Vodafone UK", "Europe"),
    Carrier("vfde", "Vodafone Germany", "Europe"),
    Carrier("vfit", "Vodafone Italy", "Europe"),
    Carrier("vfes", "Vodafone Spain", "Europe"),
    Carrier("vfnl", "Vodafone Netherlands", "Europe"),
    Carrier("vfpt", "Vodafone Portugal", "Europe"),
    Carrier("vfgr", "Vodafone Greece", "Europe"),
    Carrier("vfro", "Vodafone Romania", "Europe"),
    Carrier("vfhu", "Vodafone Hungary", "Europe"),
    Carrier("vfcz", "Vodafone Czech Republic", "Europe"),
    Carrier("vfal", "Vodafone Albania", "Europe"),
    Carrier("dteu", "Deutsche Telekom EU", "Europe"),
    Carrier("dtde", "Deutsche Telekom Germany", "Europe"),
    Carrier("dtgr", "Deutsche Telekom Greece", "Europe"),
    Carrier("dthu", "Deutsche Telekom Hungary", "Europe"),
    Carrier("dtpl", "Deutsche Telekom Poland", "Europe"),
    Carrier("dtcz", "Deutsche Telekom Czech Republic", "Europe"),
    Carrier("dtsk", "Deutsche Telekom Slovakia", "Europe"),
    Carrier("dthr", "Deutsche Telekom Croatia", "Europe"),
    Carrier("dtmk", "Deutsche Telekom North Macedonia", "Europe"),
    Carrier("dtme", "Deutsche Telekom Montenegro", "Europe"),
    Carrier("tmobile", "T-Mobile Europe", "Europe"),
    Carrier("tmoeu", "T-Mobile EU", "Europe"),
    Carrier("tmode", "T-Mobile Germany", "Europe"),
    Carrier("tmocz", "T-Mobile Czech Republic", "Europe"),
    Carrier("tmohu", "T-Mobile Hungary", "Europe"),
    Carrier("tmopl", "T-Mobile Poland", "Europe"),
    Carrier("tmonl", "T-Mobile Netherlands", "Europe"),
    Carrier("tmoat", "T-Mobile Austria", "Europe"),
    Carrier("orange", "Orange Europe", "Europe"),
    Carrier("orangefr", "Orange France", "Europe"),
    Carrier("orangees", "Orange Spain", "Europe"),
    Carrier("orangepl", "Orange Poland", "Europe"),
    Carrier("orangero", "Orange Romania", "Europe"),
    Carrier("orangebe", "Orange Belgium", "Europe"),
    Carrier("orangelu", "Orange Luxembourg", "Europe"),
    Carrier("orangesk", "Orange Slovakia", "Europe"),
    Carrier("orangemd", "Orange Moldova", "Europe"),
    Carrier("sfr", "SFR France", "Europe"),
    Carrier("bouygues", "Bouygues Telecom France", "Europe"),
    Carrier("free", "Free Mobile France", "Europe"),
    Carrier("windit", "Wind Italy", "Europe"),
    Carrier("h3g", "Hutchison 3G Europe", "Europe"),
    Carrier("3it", "Three Italy", "Europe"),
    Carrier("3at", "Three Austria", "Europe"),
    Carrier("3dk", "Three Denmark", "Europe"),
    Carrier("3se", "Three Sweden", "Europe"),
    Carrier("o2de", "O2 Germany", "Europe"),
    Carrier("o2cz", "O2 Czech Republic", "Europe"),
    Carrier("play", "Play Poland", "Europe"),
    Carrier("tele2", "Tele2 Europe", "Europe"),
    Carrier("telenor", "Telenor Europe", "Europe"),
    Carrier("telia", "Telia Europe", "Europe"),
    Carrier("dna", "DNA Finland", "Europe"),
    Carrier("elisa", "Elisa Finland", "Europe"),
    Carrier("a1at", "A1 Austria", "Europe"),
    Carrier("a1bg", "A1 Bulgaria", "Europe"),
    Carrier("a1hr", "A1 Croatia", "Europe"),
    Carrier("a1si", "A1 Slovenia", "Europe"),
    Carrier("magenta", "Magenta Telekom", "Europe"),
    Carrier("yettel", "Yettel Europe", "Europe"),
    Carrier("vivacom", "Vivacom Bulgaria", "Europe"),
    Carrier("cosmote", "Cosmote Greece", "Europe"),
    Carrier("swisscom", "Swisscom Switzerland", "Europe"),
    Carrier("sunrise", "Sunrise Switzerland", "Europe"),
    Carrier("salt", "Salt Switzerland", "Europe"),
    Carrier("proximus", "Proximus Belgium", "Europe"),
    Carrier("base", "BASE Belgium", "Europe"),
    Carrier("kpn", "KPN Netherlands", "Europe"),
    Carrier("telenet", "Telenet Belgium", "Europe"),
    Carrier("ziggo", "Ziggo Netherlands", "Europe"),
    Carrier("ee", "EE UK (alt)", "Europe"),
    Carrier("bt", "BT Mobile UK", "Europe"),
    Carrier("sky", "Sky Mobile UK", "Europe"),
    Carrier("virgin", "Virgin Media UK", "Europe"),
    Carrier("giffgaff", "giffgaff UK", "Europe"),
    Carrier("lycamobile", "Lycamobile Europe", "Europe"),
    Carrier("lebara", "Lebara Europe", "Europe"),
    Carrier("aldi", "ALDI Talk Germany", "Europe"),
    Carrier("lidl", "Lidl Connect Germany", "Europe"),
    Carrier("simyo", "Simyo Germany", "Europe"),
    Carrier("blau", "Blau Germany", "Europe"),
    Carrier("congstar", "Congstar Germany", "Europe"),
    Carrier("otelo", "Otelo Germany", "Europe"),
    Carrier("fyve", "FYVE Germany", "Europe"),
    Carrier("tchibo", "Tchibo Mobil Germany", "Europe"),
    Carrier("netzclub", "Netzclub Germany", "Europe"),
    Carrier("edeka", "EDEKA Smart Germany", "Europe"),
    # =====================================================================
    # North America
    # =====================================================================
    Carrier("retus", "Retail US", "North America"),
    Carrier("vzw", "Verizon Wireless", "North America"),
    Carrier("tmo", "T-Mobile US", "North America"),
    Carrier("att", "AT&T US", "North America"),
    Carrier("sprint", "Sprint US", "North America"),
    Carrier("usc", "US Cellular", "North America"),
    Carrier("fi", "Google Fi", "North America"),
    Carrier("comcast", "Xfinity Mobile", "North America"),
    Carrier("spectrum", "Spectrum Mobile", "North America"),
    Carrier("retca", "Retail Canada", "North America"),
    Carrier("bellca", "Bell Canada", "North America"),
    Carrier("rcica", "Rogers Canada", "North America"),
    Carrier("rgrca", "Rogers Canada (alt)", "North America"),
    Carrier("tkpca", "TELUS Canada", "North America"),
    Carrier("koodo", "Koodo Mobile Canada", "North America"),
    Carrier("fido", "Fido Canada", "North America"),
    Carrier("virgin_ca", "Virgin Plus Canada", "North America"),
    Carrier("shaw", "Shaw Mobile Canada", "North America"),
    Carrier("freedom", "Freedom Mobile Canada", "North America"),
    Carrier("videotron", "Vidéotron Canada", "North America"),
    Carrier("sasktel", "SaskTel Canada", "North America"),
    Carrier("mts", "MTS Canada", "North America"),
    Carrier("telus", "TELUS Canada (alt)", "North America"),
    Carrier("rogers", "Rogers Canada (code)", "North America"),
    Carrier("cricket", "Cricket Wireless US", "North America"),
    Carrier("boost", "Boost Mobile US", "North America"),
    Carrier("metro", "Metro by T-Mobile US", "North America"),
    Carrier("tracfone", "TracFone US", "North America"),
    Carrier("straighttalk", "Straight Talk US", "North America"),
    Carrier("simplemobile", "Simple Mobile US", "North America"),
    Carrier("totalwireless", "Total Wireless US", "North America"),
    Carrier("mintmobile", "Mint Mobile US", "North America"),
    Carrier("visible", "Visible US", "North America"),
    Carrier("xfinity", "Xfinity Mobile US (alt)", "North America"),
    Carrier("ting", "Ting Mobile US", "North America"),
    Carrier("republic", "Republic Wireless US", "North America"),
    Carrier("consumer_cellular", "Consumer Cellular US", "North America"),
    Carrier("h2o", "H2O Wireless US", "North America"),
    Carrier("lycaus", "Lycamobile US", "North America"),
    Carrier("ultra", "Ultra Mobile US", "North America"),
    Carrier("red_pocket", "Red Pocket Mobile US", "North America"),
    Carrier("gen_mobile", "Gen Mobile US", "North America"),
    Carrier("net10", "Net10 Wireless US", "North America"),
    Carrier("walmart", "Walmart Family Mobile US", "North America"),
    Carrier("safelink", "SafeLink Wireless US", "North America"),
    Carrier("qlink", "QLink Wireless US", "North America"),
    Carrier("assurance", "Assurance Wireless US", "North America"),
    Carrier("puretalk", "PureTalk US", "North America"),
    Carrier("credo", "CREDO Mobile US", "North America"),
    Carrier("uscellular", "US Cellular (alt)", "North America"),
    Carrier("c_spire", "C Spire US", "North America"),
    Carrier("nntelos", "nTelos US", "North America"),
    Carrier("appalachian", "Appalachian Wireless US", "North America"),
    Carrier("bluegrass", "Bluegrass Cellular US", "North America"),
    Carrier("cellcom", "Cellcom US", "North America"),
    Carrier("chat", "Chat Mobility US", "North America"),
    Carrier("commnet", "Commnet Wireless US", "North America"),
    Carrier("gci", "GCI Alaska", "North America"),
    Carrier("illiad", "Illiad Wireless US", "North America"),
    Carrier("inland", "Inland Cellular US", "North America"),
    Carrier("iwireless", "iWireless US", "North America"),
    Carrier("nex_tech", "Nex-Tech Wireless US", "North America"),
    Carrier("northeast", "Northeast Wireless US", "North America"),
    Carrier("panhandle", "Panhandle Wireless US", "North America"),
    Carrier("syringa", "Syringa Wireless US", "North America"),
    Carrier("thumb", "Thumb Cellular US", "North America"),
    Carrier("united", "United Wireless US", "North America"),
    Carrier("viaero", "Viaero Wireless US", "North America"),
    Carrier("pine", "Pine Cellular US", "North America"),
    Carrier("strata", "Strata Networks US", "North America"),
    # =====================================================================
    # Asia
    # =====================================================================
    Carrier("retin", "Retail India", "Asia"),
    Carrier("retcn", "Retail China", "Asia"),
    Carrier("retapac", "Retail Asia Pacific", "Asia"),
    Carrier("retapac_np", "Retail Asia Pacific (NP)", "Asia"),
    Carrier("retasia", "Retail Asia", "Asia"),
    Carrier("retjp", "Retail Japan", "Asia"),
    Carrier("retkr", "Retail Korea", "Asia"),
    Carrier("rettw", "Retail Taiwan", "Asia"),
    Carrier("retsg", "Retail Singapore", "Asia"),
    Carrier("retmy", "Retail Malaysia", "Asia"),
    Carrier("retph", "Retail Philippines", "Asia"),
    Carrier("retid", "Retail Indonesia", "Asia"),
    Carrier("retth", "Retail Thailand", "Asia"),
    Carrier("retpk", "Retail Pakistan", "Asia"),
    Carrier("retbd", "Retail Bangladesh", "Asia"),
    Carrier("retlk", "Retail Sri Lanka", "Asia"),
    Carrier("retvn", "Retail Vietnam", "Asia"),
    Carrier("retkh", "Retail Cambodia", "Asia"),
    Carrier("retla_asia", "Retail Laos", "Asia"),
    Carrier("retmm", "Retail Myanmar", "Asia"),
    Carrier("rethk", "Retail Hong Kong", "Asia"),
    Carrier("retmo", "Retail Macau", "Asia"),
    Carrier("jio", "Jio India", "Asia"),
    Carrier("airtel", "Airtel India", "Asia"),
    Carrier("bsnl", "BSNL India", "Asia"),
    Carrier("idea", "Idea India", "Asia"),
    Carrier("vi_in", "Vi India", "Asia"),
    Carrier("mtnl", "MTNL India", "Asia"),
    Carrier("csl", "CSL Hong Kong", "Asia"),
    Carrier("smartone", "SmarTone Hong Kong", "Asia"),
    Carrier("pccw", "PCCW Hong Kong", "Asia"),
    Carrier("three_hk", "Three Hong Kong", "Asia"),
    Carrier("cmhk", "China Mobile Hong Kong", "Asia"),
    Carrier("chunghwa", "Chunghwa Telecom Taiwan", "Asia"),
    Carrier("taiwanstar", "Taiwan Star", "Asia"),
    Carrier("fareastone", "Far EasTone Taiwan", "Asia"),
    Carrier("apt", "Asia Pacific Telecom Taiwan", "Asia"),
    Carrier("starhub", "StarHub Singapore", "Asia"),
    Carrier("m1", "M1 Singapore", "Asia"),
    Carrier("singtel", "Singtel Singapore", "Asia"),
    Carrier("simba", "SIMBA Singapore", "Asia"),
    Carrier("digi", "Digi Malaysia", "Asia"),
    Carrier("maxis", "Maxis Malaysia", "Asia"),
    Carrier("celcom", "Celcom Malaysia", "Asia"),
    Carrier("umobile", "U Mobile Malaysia", "Asia"),
    Carrier("dtac", "DTAC Thailand", "Asia"),
    Carrier("ais", "AIS Thailand", "Asia"),
    Carrier("trueh", "TrueMove H Thailand", "Asia"),
    Carrier("globe", "Globe Philippines", "Asia"),
    Carrier("smart_ph", "Smart Philippines", "Asia"),
    Carrier("sun", "Sun Cellular Philippines", "Asia"),
    Carrier("dito", "DITO Philippines", "Asia"),
    Carrier("telkomsel", "Telkomsel Indonesia", "Asia"),
    Carrier("indosat", "Indosat Indonesia", "Asia"),
    Carrier("xl", "XL Axiata Indonesia", "Asia"),
    Carrier("three_id", "Three Indonesia", "Asia"),
    Carrier("smartfren", "Smartfren Indonesia", "Asia"),
    Carrier("axis", "Axis Indonesia", "Asia"),
    Carrier("sk", "SK Telecom Korea", "Asia"),
    Carrier("kt", "KT Korea", "Asia"),
    Carrier("lgu", "LG U+ Korea", "Asia"),
    Carrier("docomo", "NTT Docomo Japan", "Asia"),
    Carrier("au", "au by KDDI Japan", "Asia"),
    Carrier("softbank", "SoftBank Japan", "Asia"),
    Carrier("rakuten", "Rakuten Mobile Japan", "Asia"),
    Carrier("ymobile", "Y!mobile Japan", "Asia"),
    Carrier("linemo", "LINEMO Japan", "Asia"),
    # =====================================================================
    # Africa
    # =====================================================================
    Carrier("retza", "Retail South Africa", "Africa"),
    Carrier("retke", "Retail Kenya", "Africa"),
    Carrier("retng", "Retail Nigeria", "Africa"),
    Carrier("reteg", "Retail Egypt", "Africa"),
    Carrier("retgh", "Retail Ghana", "Africa"),
    Carrier("rettz", "Retail Tanzania", "Africa"),
    Carrier("retug", "Retail Uganda", "Africa"),
    Carrier("retma", "Retail Morocco", "Africa"),
    Carrier("retdz", "Retail Algeria", "Africa"),
    Carrier("rettn", "Retail Tunisia", "Africa"),
    Carrier("retsn", "Retail Senegal", "Africa"),
    Carrier("retci", "Retail Côte d'Ivoire", "Africa"),
    Carrier("retcm", "Retail Cameroon", "Africa"),
    Carrier("retmz", "Retail Mozambique", "Africa"),
    Carrier("retao", "Retail Angola", "Africa"),
    Carrier("retzw", "Retail Zimbabwe", "Africa"),
    Carrier("retmw", "Retail Malawi", "Africa"),
    Carrier("retbw", "Retail Botswana", "Africa"),
    Carrier("retna", "Retail Namibia", "Africa"),
    Carrier("retmu", "Retail Mauritius", "Africa"),
    Carrier("retmg", "Retail Madagascar", "Africa"),
    Carrier("mtn", "MTN Africa", "Africa"),
    Carrier("vodacom", "Vodacom Africa", "Africa"),
    Carrier("airtel_af", "Airtel Africa", "Africa"),
    Carrier("safaricom", "Safaricom Kenya", "Africa"),
    Carrier("glo", "Globacom Nigeria", "Africa"),
    Carrier("etisalat_ng", "Etisalat Nigeria", "Africa"),
    Carrier("cell_c", "Cell C South Africa", "Africa"),
    Carrier("rain", "Rain South Africa", "Africa"),
    Carrier("telkom_za", "Telkom South Africa", "Africa"),
    Carrier("orange_af", "Orange Africa", "Africa"),
    # =====================================================================
    # Middle East
    # =====================================================================
    Carrier("retae", "Retail UAE", "Middle East"),
    Carrier("retsa", "Retail Saudi Arabia", "Middle East"),
    Carrier("retiq", "Retail Iraq", "Middle East"),
    Carrier("retkw", "Retail Kuwait", "Middle East"),
    Carrier("retqa", "Retail Qatar", "Middle East"),
    Carrier("retbh", "Retail Bahrain", "Middle East"),
    Carrier("retom", "Retail Oman", "Middle East"),
    Carrier("retjo", "Retail Jordan", "Middle East"),
    Carrier("retlb", "Retail Lebanon", "Middle East"),
    Carrier("retps", "Retail Palestine", "Middle East"),
    Carrier("reil", "Retail Israel", "Middle East"),
    Carrier("reteg_me", "Retail Egypt (Middle East channel)", "Middle East"),
    Carrier("stc", "STC Saudi Arabia", "Middle East"),
    Carrier("zain", "Zain Middle East", "Middle East"),
    Carrier("du", "du UAE", "Middle East"),
    Carrier("etisalat", "Etisalat UAE", "Middle East"),
    Carrier("ooredoo", "Ooredoo Middle East", "Middle East"),
    Carrier("mobily", "Mobily Saudi Arabia", "Middle East"),
    Carrier("jawwal", "Jawwal Palestine", "Middle East"),
    # =====================================================================
    # Oceania
    # =====================================================================
    Carrier("retau", "Retail Australia", "Oceania"),
    Carrier("retnz", "Retail New Zealand", "Oceania"),
    Carrier("telstra", "Telstra Australia", "Oceania"),
    Carrier("optus", "Optus Australia", "Oceania"),
    Carrier("vodafone_au", "Vodafone Australia", "Oceania"),
    Carrier("spark", "Spark New Zealand", "Oceania"),
    Carrier("two_degrees", "2degrees New Zealand", "Oceania"),
    Carrier("vodafone_nz", "Vodafone New Zealand", "Oceania"),
    # =====================================================================
    # Global / Other
    # =====================================================================
    Carrier("retail", "Retail", "Global"),
    Carrier("retgl", "Retail Global", "Global"),
    Carrier("openmarket", "Open Market Global", "Global"),
    Carrier("retear", "Retail Eastern Region", "Global"),
    Carrier("retea", "Retail East Africa / East Asia", "Global"),
    Carrier("cti", "CTI Global", "Global"),
    Carrier("amz", "Amazon Exclusive", "Global"),
    Carrier("amzn", "Amazon Exclusive (alt)", "Global"),
    Carrier("google", "Google Store", "Global"),
    Carrier("project_fi", "Google Project Fi", "Global"),
    Carrier("lenovo", "Lenovo Channel", "Global"),
    Carrier("motodev", "Motorola Developer", "Global"),
    Carrier("demo", "Demo / Showroom Units", "Global"),
    Carrier("internal", "Motorola Internal", "Global"),
    Carrier("testing", "Testing Channel", "Global"),
    Carrier("soak", "Soak Test Channel", "Global"),
    Carrier("engineering", "Engineering Builds", "Global"),
    Carrier("factory", "Factory Channel", "Global"),
]


def open_carriers() -> list[Carrier]:
    """Return only carriers that do not require serial whitelisting."""
    return [c for c in CARRIERS if c.status == "open"]


def carriers_by_region(region: str) -> list[Carrier]:
    """Return carriers for a given region."""
    return [c for c in CARRIERS if c.region == region]


def all_scannable_carriers() -> list[Carrier]:
    """Return all carriers — status is auto-detected during scan."""
    return list(CARRIERS)
