/**
 * Motorola CDS carrier database
 * 438 carrier codes across 10 regions
 * Sources: XDA, firmware repos, community testing
 */

export const CARRIERS = Object.freeze([
  // ═══ LATAM (86 carriers) ═══
  { code: 'amxmx', name: 'América Móvil México', region: 'LATAM' },
  { code: 'openmx', name: 'Open Market México', region: 'LATAM' },
  { code: 'retla', name: 'Retail Latin America', region: 'LATAM' },
  { code: 'amxla', name: 'América Móvil LATAM', region: 'LATAM' },
  { code: 'amxpe', name: 'América Móvil Perú', region: 'LATAM' },
  { code: 'tefmx', name: 'Telefónica México', region: 'LATAM' },
  { code: 'attmx', name: 'AT&T México', region: 'LATAM' },
  { code: 'retar', name: 'Retail Argentina', region: 'LATAM' },
  { code: 'amxar', name: 'América Móvil Argentina', region: 'LATAM' },
  { code: 'retmx', name: 'Retail México', region: 'LATAM' },
  { code: 'amxco', name: 'América Móvil Colombia', region: 'LATAM' },
  { code: 'amxcl', name: 'América Móvil Chile', region: 'LATAM' },
  { code: 'amxec', name: 'América Móvil Ecuador', region: 'LATAM' },
  { code: 'amxgt', name: 'América Móvil Guatemala', region: 'LATAM' },
  { code: 'amxhn', name: 'América Móvil Honduras', region: 'LATAM' },
  { code: 'amxsv', name: 'América Móvil El Salvador', region: 'LATAM' },
  { code: 'amxni', name: 'América Móvil Nicaragua', region: 'LATAM' },
  { code: 'amxcr', name: 'América Móvil Costa Rica', region: 'LATAM' },
  { code: 'amxpa', name: 'América Móvil Panamá', region: 'LATAM' },
  { code: 'amxdo', name: 'América Móvil Dominican Republic', region: 'LATAM' },
  { code: 'amxuy', name: 'América Móvil Uruguay', region: 'LATAM' },
  { code: 'amxpy', name: 'América Móvil Paraguay', region: 'LATAM' },
  { code: 'amxbo', name: 'América Móvil Bolivia', region: 'LATAM' },
  { code: 'amxve', name: 'América Móvil Venezuela', region: 'LATAM' },
  { code: 'tefcl', name: 'Telefónica Chile', region: 'LATAM' },
  { code: 'tefpe', name: 'Telefónica Perú', region: 'LATAM' },
  { code: 'tefco', name: 'Telefónica Colombia', region: 'LATAM' },
  { code: 'tefec', name: 'Telefónica Ecuador', region: 'LATAM' },
  { code: 'tefve', name: 'Telefónica Venezuela', region: 'LATAM' },
  { code: 'tefgt', name: 'Telefónica Guatemala', region: 'LATAM' },
  { code: 'tefpa', name: 'Telefónica Panamá', region: 'LATAM' },
  { code: 'tefni', name: 'Telefónica Nicaragua', region: 'LATAM' },
  { code: 'tefcr', name: 'Telefónica Costa Rica', region: 'LATAM' },
  { code: 'tefhn', name: 'Telefónica Honduras', region: 'LATAM' },
  { code: 'tefsv', name: 'Telefónica El Salvador', region: 'LATAM' },
  { code: 'tclmx', name: 'Telcel México', region: 'LATAM' },
  { code: 'openla', name: 'Open Market LATAM', region: 'LATAM' },
  { code: 'retcl', name: 'Retail Chile', region: 'LATAM' },
  { code: 'retpe', name: 'Retail Perú', region: 'LATAM' },
  { code: 'retco', name: 'Retail Colombia', region: 'LATAM' },
  { code: 'retec', name: 'Retail Ecuador', region: 'LATAM' },
  { code: 'retgt', name: 'Retail Guatemala', region: 'LATAM' },
  { code: 'rethn', name: 'Retail Honduras', region: 'LATAM' },
  { code: 'retsv', name: 'Retail El Salvador', region: 'LATAM' },
  { code: 'retni', name: 'Retail Nicaragua', region: 'LATAM' },
  { code: 'retcr', name: 'Retail Costa Rica', region: 'LATAM' },
  { code: 'retpa', name: 'Retail Panamá', region: 'LATAM' },
  { code: 'retdo', name: 'Retail Dominican Republic', region: 'LATAM' },
  { code: 'retuy', name: 'Retail Uruguay', region: 'LATAM' },
  { code: 'retpy', name: 'Retail Paraguay', region: 'LATAM' },
  { code: 'retbo', name: 'Retail Bolivia', region: 'LATAM' },
  { code: 'retve', name: 'Retail Venezuela', region: 'LATAM' },
  { code: 'claromx', name: 'Claro México', region: 'LATAM' },
  { code: 'clarobr', name: 'Claro Brazil (LATAM channel)', region: 'LATAM' },
  { code: 'claroco', name: 'Claro Colombia', region: 'LATAM' },
  { code: 'claroar', name: 'Claro Argentina', region: 'LATAM' },
  { code: 'clarocl', name: 'Claro Chile', region: 'LATAM' },
  { code: 'clarope', name: 'Claro Perú', region: 'LATAM' },
  { code: 'claroec', name: 'Claro Ecuador', region: 'LATAM' },
  { code: 'clarogt', name: 'Claro Guatemala', region: 'LATAM' },
  { code: 'claropy', name: 'Claro Paraguay', region: 'LATAM' },
  { code: 'clarouy', name: 'Claro Uruguay', region: 'LATAM' },
  { code: 'movla', name: 'Movistar LATAM', region: 'LATAM' },
  { code: 'mstla', name: 'Movistar LATAM (alt)', region: 'LATAM' },
  { code: 'mstcl', name: 'Movistar Chile (alt)', region: 'LATAM' },
  { code: 'movcl', name: 'Movistar Chile', region: 'LATAM' },
  { code: 'movpe', name: 'Movistar Perú', region: 'LATAM' },
  { code: 'movco', name: 'Movistar Colombia', region: 'LATAM' },
  { code: 'movmx', name: 'Movistar México', region: 'LATAM' },
  { code: 'movgt', name: 'Movistar Guatemala', region: 'LATAM' },
  { code: 'altmx', name: 'Altán México', region: 'LATAM' },
  { code: 'niipe', name: 'NII Perú (Nextel)', region: 'LATAM' },
  { code: 'pcspr', name: 'PCS Puerto Rico', region: 'LATAM' },
  { code: 'unefon', name: 'Unefon México', region: 'LATAM' },
  { code: 'iusacell', name: 'Iusacell México', region: 'LATAM' },
  { code: 'maxcom', name: 'Maxcom México', region: 'LATAM' },
  { code: 'izzi', name: 'Izzi Telecom México', region: 'LATAM' },
  { code: 'bait', name: 'BAIT México', region: 'LATAM' },
  { code: 'diri', name: 'Diri México', region: 'LATAM' },
  { code: 'oxxo', name: 'OXXO Cel México', region: 'LATAM' },
  { code: 'coppel', name: 'Coppel Cel México', region: 'LATAM' },
  { code: 'megacable', name: 'Megacable Móvil México', region: 'LATAM' },
  { code: 'totalplay', name: 'Totalplay Móvil México', region: 'LATAM' },

  // ═══ Brazil (11 carriers) ═══
  { code: 'retbr', name: 'Retail Brazil', region: 'Brazil' },
  { code: 'amxbr', name: 'América Móvil Brazil', region: 'Brazil' },
  { code: 'tefbr', name: 'Telefónica Brazil', region: 'Brazil' },
  { code: 'timbr', name: 'TIM Brazil', region: 'Brazil' },
  { code: 'vivobr', name: 'Vivo Brazil', region: 'Brazil' },
  { code: 'oibr', name: 'Oi Brazil', region: 'Brazil' },
  { code: 'nextel', name: 'Nextel Brazil', region: 'Brazil' },
  { code: 'claro', name: 'Claro Brazil', region: 'Brazil' },
  { code: 'algar', name: 'Algar Telecom Brazil', region: 'Brazil' },
  { code: 'surf', name: 'Surf Telecom Brazil', region: 'Brazil' },
  { code: 'sercomtel', name: 'Sercomtel Brazil', region: 'Brazil' },

  // ═══ Europe (102 carriers) ═══
  { code: 'reteu', name: 'Retail Europe', region: 'Europe' },
  { code: 'retgb', name: 'Retail UK', region: 'Europe' },
  { code: 'o2gb', name: 'O2 UK', region: 'Europe' },
  { code: 'eegb', name: 'EE UK', region: 'Europe' },
  { code: 'vfeu', name: 'Vodafone Europe', region: 'Europe' },
  { code: '3gb', name: 'Three UK', region: 'Europe' },
  { code: 'demogb', name: 'Demo UK', region: 'Europe' },
  { code: 'pluspl', name: 'Plus Poland', region: 'Europe' },
  { code: 'retde', name: 'Retail Germany', region: 'Europe' },
  { code: 'retfr', name: 'Retail France', region: 'Europe' },
  { code: 'retes', name: 'Retail Spain', region: 'Europe' },
  { code: 'retit', name: 'Retail Italy', region: 'Europe' },
  { code: 'retnl', name: 'Retail Netherlands', region: 'Europe' },
  { code: 'retpl', name: 'Retail Poland', region: 'Europe' },
  { code: 'retpt', name: 'Retail Portugal', region: 'Europe' },
  { code: 'retat', name: 'Retail Austria', region: 'Europe' },
  { code: 'retbe', name: 'Retail Belgium', region: 'Europe' },
  { code: 'retch', name: 'Retail Switzerland', region: 'Europe' },
  { code: 'retcz', name: 'Retail Czech Republic', region: 'Europe' },
  { code: 'retdk', name: 'Retail Denmark', region: 'Europe' },
  { code: 'retfi', name: 'Retail Finland', region: 'Europe' },
  { code: 'retgr', name: 'Retail Greece', region: 'Europe' },
  { code: 'rethr', name: 'Retail Croatia', region: 'Europe' },
  { code: 'rethu', name: 'Retail Hungary', region: 'Europe' },
  { code: 'retie', name: 'Retail Ireland', region: 'Europe' },
  { code: 'retlu', name: 'Retail Luxembourg', region: 'Europe' },
  { code: 'retno', name: 'Retail Norway', region: 'Europe' },
  { code: 'retro', name: 'Retail Romania', region: 'Europe' },
  { code: 'retse', name: 'Retail Sweden', region: 'Europe' },
  { code: 'retsi', name: 'Retail Slovenia', region: 'Europe' },
  { code: 'retsk', name: 'Retail Slovakia', region: 'Europe' },
  { code: 'retba', name: 'Retail Bosnia', region: 'Europe' },
  { code: 'retbg', name: 'Retail Bulgaria', region: 'Europe' },
  { code: 'retcy', name: 'Retail Cyprus', region: 'Europe' },
  { code: 'retee', name: 'Retail Estonia', region: 'Europe' },
  { code: 'retlv', name: 'Retail Latvia', region: 'Europe' },
  { code: 'retlt', name: 'Retail Lithuania', region: 'Europe' },
  { code: 'retmk', name: 'Retail North Macedonia', region: 'Europe' },
  { code: 'retmt', name: 'Retail Malta', region: 'Europe' },
  { code: 'retrs', name: 'Retail Serbia', region: 'Europe' },
  { code: 'retua', name: 'Retail Ukraine', region: 'Europe' },
  { code: 'retru', name: 'Retail Russia', region: 'Europe' },
  { code: 'openeu', name: 'Open Market Europe', region: 'Europe' },
  { code: 'vfgb', name: 'Vodafone UK', region: 'Europe' },
  { code: 'vfde', name: 'Vodafone Germany', region: 'Europe' },
  { code: 'vfit', name: 'Vodafone Italy', region: 'Europe' },
  { code: 'vfes', name: 'Vodafone Spain', region: 'Europe' },
  { code: 'vfnl', name: 'Vodafone Netherlands', region: 'Europe' },
  { code: 'vfpt', name: 'Vodafone Portugal', region: 'Europe' },
  { code: 'vfgr', name: 'Vodafone Greece', region: 'Europe' },
  { code: 'vfro', name: 'Vodafone Romania', region: 'Europe' },
  { code: 'vfhu', name: 'Vodafone Hungary', region: 'Europe' },
  { code: 'vfcz', name: 'Vodafone Czech Republic', region: 'Europe' },
  { code: 'vfal', name: 'Vodafone Albania', region: 'Europe' },
  { code: 'dteu', name: 'Deutsche Telekom EU', region: 'Europe' },
  { code: 'dtde', name: 'Deutsche Telekom Germany', region: 'Europe' },
  { code: 'dtgr', name: 'Deutsche Telekom Greece', region: 'Europe' },
  { code: 'dthu', name: 'Deutsche Telekom Hungary', region: 'Europe' },
  { code: 'dtpl', name: 'Deutsche Telekom Poland', region: 'Europe' },
  { code: 'dtcz', name: 'Deutsche Telekom Czech Republic', region: 'Europe' },
  { code: 'dtsk', name: 'Deutsche Telekom Slovakia', region: 'Europe' },
  { code: 'dthr', name: 'Deutsche Telekom Croatia', region: 'Europe' },
  { code: 'dtmk', name: 'Deutsche Telekom North Macedonia', region: 'Europe' },
  { code: 'dtme', name: 'Deutsche Telekom Montenegro', region: 'Europe' },
  { code: 'tmobile', name: 'T-Mobile Europe', region: 'Europe' },
  { code: 'tmoeu', name: 'T-Mobile EU', region: 'Europe' },
  { code: 'tmode', name: 'T-Mobile Germany', region: 'Europe' },
  { code: 'tmocz', name: 'T-Mobile Czech Republic', region: 'Europe' },
  { code: 'tmohu', name: 'T-Mobile Hungary', region: 'Europe' },
  { code: 'tmopl', name: 'T-Mobile Poland', region: 'Europe' },
  { code: 'tmonl', name: 'T-Mobile Netherlands', region: 'Europe' },
  { code: 'tmoat', name: 'T-Mobile Austria', region: 'Europe' },
  { code: 'orange', name: 'Orange Europe', region: 'Europe' },
  { code: 'orangefr', name: 'Orange France', region: 'Europe' },
  { code: 'orangees', name: 'Orange Spain', region: 'Europe' },
  { code: 'orangepl', name: 'Orange Poland', region: 'Europe' },
  { code: 'orangero', name: 'Orange Romania', region: 'Europe' },
  { code: 'orangebe', name: 'Orange Belgium', region: 'Europe' },
  { code: 'orangelu', name: 'Orange Luxembourg', region: 'Europe' },
  { code: 'orangesk', name: 'Orange Slovakia', region: 'Europe' },
  { code: 'orangemd', name: 'Orange Moldova', region: 'Europe' },
  { code: 'sfr', name: 'SFR France', region: 'Europe' },
  { code: 'bouygues', name: 'Bouygues Telecom France', region: 'Europe' },
  { code: 'free', name: 'Free Mobile France', region: 'Europe' },
  { code: 'windit', name: 'Wind Italy', region: 'Europe' },
  { code: 'h3g', name: 'Hutchison 3G Europe', region: 'Europe' },
  { code: '3it', name: 'Three Italy', region: 'Europe' },
  { code: '3at', name: 'Three Austria', region: 'Europe' },
  { code: '3dk', name: 'Three Denmark', region: 'Europe' },
  { code: '3se', name: 'Three Sweden', region: 'Europe' },
  { code: 'o2de', name: 'O2 Germany', region: 'Europe' },
  { code: 'o2cz', name: 'O2 Czech Republic', region: 'Europe' },
  { code: 'play', name: 'Play Poland', region: 'Europe' },
  { code: 'tele2', name: 'Tele2 Europe', region: 'Europe' },
  { code: 'telenor', name: 'Telenor Europe', region: 'Europe' },
  { code: 'telia', name: 'Telia Europe', region: 'Europe' },
  { code: 'dna', name: 'DNA Finland', region: 'Europe' },
  { code: 'elisa', name: 'Elisa Finland', region: 'Europe' },
  { code: 'a1at', name: 'A1 Austria', region: 'Europe' },
  { code: 'a1bg', name: 'A1 Bulgaria', region: 'Europe' },
  { code: 'a1hr', name: 'A1 Croatia', region: 'Europe' },
  { code: 'a1si', name: 'A1 Slovenia', region: 'Europe' },

  // ═══ North America (71 carriers) ═══
  { code: 'retus', name: 'Retail US', region: 'North America' },
  { code: 'retca', name: 'Retail Canada', region: 'North America' },
  { code: 'att', name: 'AT&T US', region: 'North America' },
  { code: 'tmo', name: 'T-Mobile US', region: 'North America' },
  { code: 'vzw', name: 'Verizon US', region: 'North America' },
  { code: 'sprint', name: 'Sprint US', region: 'North America' },
  { code: 'usc', name: 'US Cellular', region: 'North America' },
  { code: 'comcast', name: 'Xfinity Mobile US', region: 'North America' },
  { code: 'dish', name: 'DISH Network US', region: 'North America' },
  { code: 'spectrum', name: 'Spectrum Mobile US', region: 'North America' },
  { code: 'charter', name: 'Charter Communications US', region: 'North America' },
  { code: 'altice', name: 'Altice Mobile US', region: 'North America' },
  { code: 'fi', name: 'Google Fi US', region: 'North America' },
  { code: 'openus', name: 'Open Market US', region: 'North America' },
  { code: 'firstnet', name: 'FirstNet US', region: 'North America' },
  { code: 'bell', name: 'Bell Canada', region: 'North America' },
  { code: 'robca', name: 'Rogers Canada', region: 'North America' },
  { code: 'tls', name: 'TELUS Canada', region: 'North America' },
  { code: 'shaw', name: 'Shaw Mobile Canada', region: 'North America' },
  { code: 'freedom', name: 'Freedom Mobile Canada', region: 'North America' },
  { code: 'videotron', name: 'Vidéotron Canada', region: 'North America' },
  { code: 'sasktel', name: 'SaskTel Canada', region: 'North America' },
  { code: 'mts', name: 'MTS Canada', region: 'North America' },
  { code: 'telus', name: 'TELUS Canada (alt)', region: 'North America' },
  { code: 'rogers', name: 'Rogers Canada (code)', region: 'North America' },
  { code: 'cricket', name: 'Cricket Wireless US', region: 'North America' },
  { code: 'boost', name: 'Boost Mobile US', region: 'North America' },
  { code: 'metro', name: 'Metro by T-Mobile US', region: 'North America' },
  { code: 'tracfone', name: 'TracFone US', region: 'North America' },
  { code: 'straighttalk', name: 'Straight Talk US', region: 'North America' },
  { code: 'simplemobile', name: 'Simple Mobile US', region: 'North America' },
  { code: 'totalwireless', name: 'Total Wireless US', region: 'North America' },
  { code: 'mintmobile', name: 'Mint Mobile US', region: 'North America' },
  { code: 'visible', name: 'Visible US', region: 'North America' },
  { code: 'xfinity', name: 'Xfinity Mobile US (alt)', region: 'North America' },
  { code: 'ting', name: 'Ting Mobile US', region: 'North America' },
  { code: 'republic', name: 'Republic Wireless US', region: 'North America' },
  { code: 'consumer_cellular', name: 'Consumer Cellular US', region: 'North America' },
  { code: 'h2o', name: 'H2O Wireless US', region: 'North America' },
  { code: 'lycaus', name: 'Lycamobile US', region: 'North America' },
  { code: 'ultra', name: 'Ultra Mobile US', region: 'North America' },
  { code: 'red_pocket', name: 'Red Pocket Mobile US', region: 'North America' },
  { code: 'gen_mobile', name: 'Gen Mobile US', region: 'North America' },
  { code: 'net10', name: 'Net10 Wireless US', region: 'North America' },
  { code: 'walmart', name: 'Walmart Family Mobile US', region: 'North America' },
  { code: 'safelink', name: 'SafeLink Wireless US', region: 'North America' },
  { code: 'qlink', name: 'QLink Wireless US', region: 'North America' },
  { code: 'assurance', name: 'Assurance Wireless US', region: 'North America' },
  { code: 'puretalk', name: 'PureTalk US', region: 'North America' },
  { code: 'credo', name: 'CREDO Mobile US', region: 'North America' },
  { code: 'uscellular', name: 'US Cellular (alt)', region: 'North America' },
  { code: 'c_spire', name: 'C Spire US', region: 'North America' },
  { code: 'nntelos', name: 'nTelos US', region: 'North America' },
  { code: 'appalachian', name: 'Appalachian Wireless US', region: 'North America' },
  { code: 'bluegrass', name: 'Bluegrass Cellular US', region: 'North America' },
  { code: 'cellcom', name: 'Cellcom US', region: 'North America' },
  { code: 'chat', name: 'Chat Mobility US', region: 'North America' },
  { code: 'commnet', name: 'Commnet Wireless US', region: 'North America' },
  { code: 'gci', name: 'GCI Alaska', region: 'North America' },
  { code: 'illiad', name: 'Illiad Wireless US', region: 'North America' },
  { code: 'inland', name: 'Inland Cellular US', region: 'North America' },
  { code: 'iwireless', name: 'iWireless US', region: 'North America' },
  { code: 'nex_tech', name: 'Nex-Tech Wireless US', region: 'North America' },
  { code: 'northeast', name: 'Northeast Wireless US', region: 'North America' },
  { code: 'panhandle', name: 'Panhandle Wireless US', region: 'North America' },
  { code: 'syringa', name: 'Syringa Wireless US', region: 'North America' },
  { code: 'thumb', name: 'Thumb Cellular US', region: 'North America' },
  { code: 'united', name: 'United Wireless US', region: 'North America' },
  { code: 'viaero', name: 'Viaero Wireless US', region: 'North America' },
  { code: 'pine', name: 'Pine Cellular US', region: 'North America' },
  { code: 'strata', name: 'Strata Networks US', region: 'North America' },

  // ═══ Asia (68 carriers) ═══
  { code: 'retin', name: 'Retail India', region: 'Asia' },
  { code: 'retcn', name: 'Retail China', region: 'Asia' },
  { code: 'retapac', name: 'Retail Asia Pacific', region: 'Asia' },
  { code: 'retapac_np', name: 'Retail Asia Pacific (NP)', region: 'Asia' },
  { code: 'retasia', name: 'Retail Asia', region: 'Asia' },
  { code: 'retjp', name: 'Retail Japan', region: 'Asia' },
  { code: 'retkr', name: 'Retail Korea', region: 'Asia' },
  { code: 'rettw', name: 'Retail Taiwan', region: 'Asia' },
  { code: 'retsg', name: 'Retail Singapore', region: 'Asia' },
  { code: 'retmy', name: 'Retail Malaysia', region: 'Asia' },
  { code: 'retph', name: 'Retail Philippines', region: 'Asia' },
  { code: 'retid', name: 'Retail Indonesia', region: 'Asia' },
  { code: 'retth', name: 'Retail Thailand', region: 'Asia' },
  { code: 'retpk', name: 'Retail Pakistan', region: 'Asia' },
  { code: 'retbd', name: 'Retail Bangladesh', region: 'Asia' },
  { code: 'retlk', name: 'Retail Sri Lanka', region: 'Asia' },
  { code: 'retvn', name: 'Retail Vietnam', region: 'Asia' },
  { code: 'retkh', name: 'Retail Cambodia', region: 'Asia' },
  { code: 'retla_asia', name: 'Retail Laos', region: 'Asia' },
  { code: 'retmm', name: 'Retail Myanmar', region: 'Asia' },
  { code: 'rethk', name: 'Retail Hong Kong', region: 'Asia' },
  { code: 'retmo', name: 'Retail Macau', region: 'Asia' },
  { code: 'jio', name: 'Jio India', region: 'Asia' },
  { code: 'airtel', name: 'Airtel India', region: 'Asia' },
  { code: 'bsnl', name: 'BSNL India', region: 'Asia' },
  { code: 'idea', name: 'Idea India', region: 'Asia' },
  { code: 'vi_in', name: 'Vi India', region: 'Asia' },
  { code: 'mtnl', name: 'MTNL India', region: 'Asia' },
  { code: 'csl', name: 'CSL Hong Kong', region: 'Asia' },
  { code: 'smartone', name: 'SmarTone Hong Kong', region: 'Asia' },
  { code: 'pccw', name: 'PCCW Hong Kong', region: 'Asia' },
  { code: 'three_hk', name: 'Three Hong Kong', region: 'Asia' },
  { code: 'cmhk', name: 'China Mobile Hong Kong', region: 'Asia' },
  { code: 'chunghwa', name: 'Chunghwa Telecom Taiwan', region: 'Asia' },
  { code: 'taiwanstar', name: 'Taiwan Star', region: 'Asia' },
  { code: 'fareastone', name: 'Far EasTone Taiwan', region: 'Asia' },
  { code: 'apt', name: 'Asia Pacific Telecom Taiwan', region: 'Asia' },
  { code: 'starhub', name: 'StarHub Singapore', region: 'Asia' },
  { code: 'm1', name: 'M1 Singapore', region: 'Asia' },
  { code: 'singtel', name: 'Singtel Singapore', region: 'Asia' },
  { code: 'simba', name: 'SIMBA Singapore', region: 'Asia' },
  { code: 'digi', name: 'Digi Malaysia', region: 'Asia' },
  { code: 'maxis', name: 'Maxis Malaysia', region: 'Asia' },
  { code: 'celcom', name: 'Celcom Malaysia', region: 'Asia' },
  { code: 'umobile', name: 'U Mobile Malaysia', region: 'Asia' },
  { code: 'dtac', name: 'DTAC Thailand', region: 'Asia' },
  { code: 'ais', name: 'AIS Thailand', region: 'Asia' },
  { code: 'trueh', name: 'TrueMove H Thailand', region: 'Asia' },
  { code: 'globe', name: 'Globe Philippines', region: 'Asia' },
  { code: 'smart_ph', name: 'Smart Philippines', region: 'Asia' },
  { code: 'sun', name: 'Sun Cellular Philippines', region: 'Asia' },
  { code: 'dito', name: 'DITO Philippines', region: 'Asia' },
  { code: 'telkomsel', name: 'Telkomsel Indonesia', region: 'Asia' },
  { code: 'indosat', name: 'Indosat Indonesia', region: 'Asia' },
  { code: 'xl', name: 'XL Axiata Indonesia', region: 'Asia' },
  { code: 'three_id', name: 'Three Indonesia', region: 'Asia' },
  { code: 'smartfren', name: 'Smartfren Indonesia', region: 'Asia' },
  { code: 'axis', name: 'Axis Indonesia', region: 'Asia' },
  { code: 'sk', name: 'SK Telecom Korea', region: 'Asia' },
  { code: 'kt', name: 'KT Korea', region: 'Asia' },
  { code: 'lgu', name: 'LG U+ Korea', region: 'Asia' },
  { code: 'docomo', name: 'NTT Docomo Japan', region: 'Asia' },
  { code: 'au', name: 'au by KDDI Japan', region: 'Asia' },
  { code: 'softbank', name: 'SoftBank Japan', region: 'Asia' },
  { code: 'rakuten', name: 'Rakuten Mobile Japan', region: 'Asia' },
  { code: 'ymobile', name: 'Y!mobile Japan', region: 'Asia' },
  { code: 'linemo', name: 'LINEMO Japan', region: 'Asia' },

  // ═══ Africa (30 carriers) ═══
  { code: 'retza', name: 'Retail South Africa', region: 'Africa' },
  { code: 'retke', name: 'Retail Kenya', region: 'Africa' },
  { code: 'retng', name: 'Retail Nigeria', region: 'Africa' },
  { code: 'reteg', name: 'Retail Egypt', region: 'Africa' },
  { code: 'retgh', name: 'Retail Ghana', region: 'Africa' },
  { code: 'rettz', name: 'Retail Tanzania', region: 'Africa' },
  { code: 'retug', name: 'Retail Uganda', region: 'Africa' },
  { code: 'retma', name: 'Retail Morocco', region: 'Africa' },
  { code: 'retdz', name: 'Retail Algeria', region: 'Africa' },
  { code: 'rettn', name: 'Retail Tunisia', region: 'Africa' },
  { code: 'retsn', name: 'Retail Senegal', region: 'Africa' },
  { code: 'retci', name: "Retail Côte d'Ivoire", region: 'Africa' },
  { code: 'retcm', name: 'Retail Cameroon', region: 'Africa' },
  { code: 'retmz', name: 'Retail Mozambique', region: 'Africa' },
  { code: 'retao', name: 'Retail Angola', region: 'Africa' },
  { code: 'retzw', name: 'Retail Zimbabwe', region: 'Africa' },
  { code: 'retmw', name: 'Retail Malawi', region: 'Africa' },
  { code: 'retbw', name: 'Retail Botswana', region: 'Africa' },
  { code: 'retna', name: 'Retail Namibia', region: 'Africa' },
  { code: 'retmu', name: 'Retail Mauritius', region: 'Africa' },
  { code: 'retmg', name: 'Retail Madagascar', region: 'Africa' },
  { code: 'mtn', name: 'MTN Africa', region: 'Africa' },
  { code: 'vodacom', name: 'Vodacom Africa', region: 'Africa' },
  { code: 'airtel_af', name: 'Airtel Africa', region: 'Africa' },
  { code: 'safaricom', name: 'Safaricom Kenya', region: 'Africa' },
  { code: 'glo', name: 'Globacom Nigeria', region: 'Africa' },
  { code: 'etisalat_ng', name: 'Etisalat Nigeria', region: 'Africa' },
  { code: 'cell_c', name: 'Cell C South Africa', region: 'Africa' },
  { code: 'rain', name: 'Rain South Africa', region: 'Africa' },
  { code: 'telkom_za', name: 'Telkom South Africa', region: 'Africa' },
  { code: 'orange_af', name: 'Orange Africa', region: 'Africa' },

  // ═══ Middle East (19 carriers) ═══
  { code: 'retae', name: 'Retail UAE', region: 'Middle East' },
  { code: 'retsa', name: 'Retail Saudi Arabia', region: 'Middle East' },
  { code: 'retiq', name: 'Retail Iraq', region: 'Middle East' },
  { code: 'retkw', name: 'Retail Kuwait', region: 'Middle East' },
  { code: 'retqa', name: 'Retail Qatar', region: 'Middle East' },
  { code: 'retbh', name: 'Retail Bahrain', region: 'Middle East' },
  { code: 'retom', name: 'Retail Oman', region: 'Middle East' },
  { code: 'retjo', name: 'Retail Jordan', region: 'Middle East' },
  { code: 'retlb', name: 'Retail Lebanon', region: 'Middle East' },
  { code: 'retps', name: 'Retail Palestine', region: 'Middle East' },
  { code: 'reil', name: 'Retail Israel', region: 'Middle East' },
  { code: 'reteg_me', name: 'Retail Egypt (Middle East channel)', region: 'Middle East' },
  { code: 'stc', name: 'STC Saudi Arabia', region: 'Middle East' },
  { code: 'zain', name: 'Zain Middle East', region: 'Middle East' },
  { code: 'du', name: 'du UAE', region: 'Middle East' },
  { code: 'etisalat', name: 'Etisalat UAE', region: 'Middle East' },
  { code: 'ooredoo', name: 'Ooredoo Middle East', region: 'Middle East' },
  { code: 'mobily', name: 'Mobily Saudi Arabia', region: 'Middle East' },
  { code: 'jawwal', name: 'Jawwal Palestine', region: 'Middle East' },

  // ═══ Oceania (8 carriers) ═══
  { code: 'retau', name: 'Retail Australia', region: 'Oceania' },
  { code: 'retnz', name: 'Retail New Zealand', region: 'Oceania' },
  { code: 'telstra', name: 'Telstra Australia', region: 'Oceania' },
  { code: 'optus', name: 'Optus Australia', region: 'Oceania' },
  { code: 'vodafone_au', name: 'Vodafone Australia', region: 'Oceania' },
  { code: 'spark', name: 'Spark New Zealand', region: 'Oceania' },
  { code: 'two_degrees', name: '2degrees New Zealand', region: 'Oceania' },
  { code: 'vodafone_nz', name: 'Vodafone New Zealand', region: 'Oceania' },

  // ═══ Global (18 carriers) ═══
  { code: 'retail', name: 'Retail', region: 'Global' },
  { code: 'retgl', name: 'Retail Global', region: 'Global' },
  { code: 'openmarket', name: 'Open Market Global', region: 'Global' },
  { code: 'retear', name: 'Retail Eastern Region', region: 'Global' },
  { code: 'retea', name: 'Retail East Africa / East Asia', region: 'Global' },
  { code: 'cti', name: 'CTI Global', region: 'Global' },
  { code: 'amz', name: 'Amazon Exclusive', region: 'Global' },
  { code: 'amzn', name: 'Amazon Exclusive (alt)', region: 'Global' },
  { code: 'google', name: 'Google Store', region: 'Global' },
  { code: 'project_fi', name: 'Google Project Fi', region: 'Global' },
  { code: 'lenovo', name: 'Lenovo Channel', region: 'Global' },
  { code: 'motodev', name: 'Motorola Developer', region: 'Global' },
  { code: 'demo', name: 'Demo / Showroom Units', region: 'Global' },
  { code: 'internal', name: 'Motorola Internal', region: 'Global' },
  { code: 'testing', name: 'Testing Channel', region: 'Global' },
  { code: 'soak', name: 'Soak Test Channel', region: 'Global' },
  { code: 'engineering', name: 'Engineering Builds', region: 'Global' },
  { code: 'factory', name: 'Factory Channel', region: 'Global' },
]);

/**
 * Find a carrier by its exact code.
 * @param {string} code - Carrier code (e.g. 'att', 'vfeu')
 * @returns {Object|undefined} Carrier object or undefined
 */
export function getCarrierByCode(code) {
  return CARRIERS.find(c => c.code === code);
}

/**
 * Get all carriers belonging to a specific region.
 * @param {string} region - Region name (e.g. 'Europe', 'LATAM')
 * @returns {Object[]} Array of matching carrier objects
 */
export function getCarriersByRegion(region) {
  return CARRIERS.filter(c => c.region === region);
}

/**
 * Search carriers by code, name, or region (case-insensitive).
 * @param {string} query - Search term
 * @returns {Object[]} Array of matching carrier objects
 */
export function searchCarriers(query) {
  const q = query.toLowerCase();
  return CARRIERS.filter(c =>
    c.code.toLowerCase().includes(q) ||
    c.name.toLowerCase().includes(q) ||
    c.region.toLowerCase().includes(q)
  );
}

/**
 * Get the number of carriers in each region.
 * @returns {Object} Map of region name to carrier count
 */
export function getRegionCounts() {
  const counts = {};
  for (const c of CARRIERS) {
    counts[c.region] = (counts[c.region] || 0) + 1;
  }
  return counts;
}

/**
 * Get all unique region names.
 * @returns {string[]} Array of region names
 */
export function getAllRegionNames() {
  return [...new Set(CARRIERS.map(c => c.region))];
}
