"""Camoufox browser session manager for Lenovo Passport login.

Uses Camoufox (anti-detect Firefox via Playwright) with:

* **TLS fingerprint spoofing** – Firefox C++-level TLS/JA3 masking
* **Real Windows 11 hardware simulation** – ``os="windows"`` generates
  coherent navigator, screen, WebGL, canvas, and audio fingerprints
* **Persistent cookies** – saved to ``~/.config/moto-ota/lenovo-browser/``
  and restored on subsequent runs
* **Real User-Agent** – generated by BrowserForge to match the spoofed
  fingerprint (Firefox on Windows)
* **GeoIP** – locale, timezone, and WebRTC location derived from the
  current IP address via ``geoip=True``
* **Humanize** – randomised cursor movements, click delays, and typing
  cadence to avoid behavioural detection

The login flow is a **two-step process**:

  1. Enter email in ``#emailOrPhoneInput`` → click **Next**
  2. Wait for ``#emailOrPhonePswInput`` → enter password → click **Next**
  3. Handle Akamai Bot Manager sensor (``_abck`` cookie) + reCAPTCHA
  4. Redirect to ``lsa.lenovo.com/Tips/lenovoIdSuccess.html?lenovoid.wust=…``
  5. Extract WUST token from the redirect URL

.. note::

   The Akamai sensor requires a **residential IP** to pass.  Data-centre
   IPs (AWS, GCP, GitHub Actions) are typically blocked.  Use a
   residential proxy or VPN when running from a server.
"""

from __future__ import annotations

import logging
import random
import re
import json
from pathlib import Path
from typing import Any, Optional
from urllib.parse import parse_qs, urlparse

logger = logging.getLogger(__name__)

# Default directory for persistent browser data
_DATA_DIR = Path.home() / ".config" / "moto-ota" / "lenovo-browser"
_COOKIES_FILE = _DATA_DIR / "cookies.json"


def _ensure_data_dir() -> Path:
    """Create and return the persistent data directory."""
    _DATA_DIR.mkdir(parents=True, exist_ok=True)
    return _DATA_DIR


def _load_cookies(path: Path | None = None) -> list[dict]:
    """Load saved cookies from disk."""
    fp = path or _COOKIES_FILE
    if fp.exists():
        try:
            return json.loads(fp.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            logger.warning("Could not load cookies from %s", fp)
    return []


def _save_cookies(cookies: list[dict], path: Path | None = None) -> None:
    """Persist cookies to disk."""
    fp = path or _COOKIES_FILE
    fp.parent.mkdir(parents=True, exist_ok=True)
    fp.write_text(json.dumps(cookies, indent=2), encoding="utf-8")
    logger.debug("Saved %d cookies to %s", len(cookies), fp)


def _human_type(page: Any, text: str) -> None:
    """Type *text* character-by-character with random delays."""
    for ch in text:
        page.keyboard.type(ch, delay=40 + (ord(ch) % 60))
        page.wait_for_timeout(random.randint(10, 30))


def _human_click(page: Any, element: Any) -> None:
    """Click on an element's bounding-box centre with slight random offset."""
    box = element.bounding_box()
    if box:
        x = box["x"] + box["width"] / 2 + random.randint(-3, 3)
        y = box["y"] + box["height"] / 2 + random.randint(-2, 2)
        page.mouse.move(x, y)
        page.wait_for_timeout(random.randint(200, 500))
        page.mouse.click(x, y)
    else:
        element.click()


def _simulate_human_browsing(page: Any) -> None:
    """Generate mouse movements, scrolls and clicks for Akamai sensor."""
    # Random mouse movements across the viewport
    for _ in range(15):
        x = random.randint(200, 1700)
        y = random.randint(100, 900)
        page.mouse.move(x, y)
        page.wait_for_timeout(random.randint(80, 350))

    page.wait_for_timeout(1500)

    # Scroll down then up (natural reading behaviour)
    for _ in range(3):
        page.mouse.wheel(0, random.randint(80, 250))
        page.wait_for_timeout(random.randint(400, 800))
    for _ in range(2):
        page.mouse.wheel(0, random.randint(-180, -40))
        page.wait_for_timeout(random.randint(400, 800))

    # Neutral click on the page body
    page.mouse.click(960, 300)
    page.wait_for_timeout(800)


def passport_login(
    username: str,
    password: str,
    *,
    lang: str = "en_US",
    headless: bool = True,
    timeout_ms: int = 90_000,
    data_dir: Path | None = None,
    proxy: dict | None = None,
) -> str:
    """Perform Lenovo Passport login using Camoufox and return the WUST token.

    Parameters
    ----------
    username:
        Lenovo ID (email address).
    password:
        Account password (encrypted client-side by the login page JS).
    lang:
        Language code for the login page (``en_US``).
    headless:
        Run Camoufox in headless mode.  Set to ``False`` when a virtual
        display (Xvfb) is available for better stealth.
    timeout_ms:
        Maximum time in milliseconds for each navigation/wait step.
    data_dir:
        Directory for persistent browser data (cookies, localStorage).
    proxy:
        Optional Playwright proxy dict, e.g.
        ``{"server": "socks5://host:port", "username": "u", "password": "p"}``.
        A **residential proxy** is recommended to bypass Akamai.

    Returns
    -------
    str
        The WUST token extracted from the success redirect URL.

    Raises
    ------
    RuntimeError
        If login fails or WUST token cannot be extracted.
    ImportError
        If camoufox is not installed.
    """
    try:
        from camoufox.sync_api import Camoufox
        from browserforge.fingerprints import Screen
    except ImportError:
        raise ImportError(
            "camoufox is required for Lenovo login.  "
            "Install it with: pip install 'camoufox[geoip]' && python -m camoufox fetch"
        )

    _ensure_data_dir()
    browser_data = data_dir or _DATA_DIR
    saved_cookies = _load_cookies()

    login_url = (
        "https://passport.lenovo.com/glbwebauthnv6/preLogin"
        "?lenovoid.action=uilogin"
        "&lenovoid.realm=lmsaclient"
        "&lenovoid.cb=https://lsa.lenovo.com/Tips/lenovoIdSuccess.html"
        f"&lenovoid.lang={lang}"
    )

    wust: Optional[str] = None

    # ── Build Camoufox launch options ────────────────────────────────
    launch_kwargs: dict = {
        "os": "windows",          # Windows 11 fingerprint
        "humanize": 2.5,          # cursor movement up to 2.5 s
        "headless": headless,
        "geoip": True,            # locale / tz from IP
        "addons": [],             # no extensions (cleaner profile)
        "i_know_what_im_doing": True,
        "screen": Screen(         # 1080p display
            min_width=1920, max_width=1920,
            min_height=1080, max_height=1080,
        ),
        "window": (1920, 1080),
        "enable_cache": True,     # persistent HTTP cache
    }
    if proxy:
        launch_kwargs["proxy"] = proxy

    with Camoufox(**launch_kwargs) as browser:
        page = browser.new_page()

        # Restore cookies from a previous session
        if saved_cookies:
            try:
                page.context.add_cookies(saved_cookies)
                logger.debug("Restored %d cookies", len(saved_cookies))
            except Exception:
                logger.warning("Could not restore cookies")

        # ── Step 1: Navigate to Passport login ───────────────────────
        logger.info("Navigating to Lenovo Passport login…")
        page.goto(login_url, wait_until="load", timeout=timeout_ms)
        logger.info("Page title: %s", page.title())

        # ── Step 2: Human interaction for Akamai sensor ──────────────
        logger.info("Simulating human interaction for Akamai sensor…")
        _simulate_human_browsing(page)
        page.wait_for_timeout(12_000)

        # Reload once to give the sensor a second pass
        page.reload(wait_until="load", timeout=timeout_ms)
        _simulate_human_browsing(page)
        page.wait_for_timeout(8_000)

        # ── Step 3: Fill email (two-step login) ──────────────────────
        logger.info("Filling email: %s", username)
        email_field = page.wait_for_selector(
            "#emailOrPhoneInput:visible", timeout=timeout_ms
        )
        _human_click(page, email_field)
        page.wait_for_timeout(600)
        _human_type(page, username)
        page.wait_for_timeout(2_000)

        # ── Step 4: Click "Next" ─────────────────────────────────────
        logger.info("Clicking Next…")
        next_btn = None
        for btn in page.query_selector_all("button:visible"):
            if "Next" in (btn.text_content() or ""):
                next_btn = btn
                break
        if next_btn:
            _human_click(page, next_btn)
        else:
            page.keyboard.press("Enter")

        # Wait for AJAX (ajaxUserRoam) and password field
        logger.info("Waiting for password field…")
        page.wait_for_timeout(10_000)

        # ── Step 5: Fill password ────────────────────────────────────
        pwd_field = (
            page.query_selector("#emailOrPhonePswInput:visible")
            or page.query_selector('input[type="password"]:visible')
        )

        if not pwd_field:
            page.wait_for_timeout(8_000)
            pwd_field = (
                page.query_selector("#emailOrPhonePswInput:visible")
                or page.query_selector('input[type="password"]:visible')
            )

        if not pwd_field:
            body_el = page.query_selector("body")
            text = body_el.inner_text() if body_el else ""
            _save_cookies(page.context.cookies())
            if "Network access error" in text:
                raise RuntimeError(
                    "Akamai bot protection blocked the request.  "
                    "Use a residential proxy: "
                    'passport_login(…, proxy={"server": "socks5://…"})'
                )
            raise RuntimeError(
                f"Password field not visible after Next click.  "
                f"Page text: {text[:300]}"
            )

        logger.info("Filling password…")
        _human_click(page, pwd_field)
        page.wait_for_timeout(500)
        _human_type(page, password)
        page.wait_for_timeout(2_000)

        # ── Step 6: Submit login form ────────────────────────────────
        logger.info("Submitting login…")
        submit_btn = None
        for btn in page.query_selector_all("button:visible"):
            text = (btn.text_content() or "").strip()
            if text in ("Next", "Sign In", "Log In"):
                submit_btn = btn
                break
        if submit_btn:
            _human_click(page, submit_btn)
        else:
            page.keyboard.press("Enter")

        # ── Step 7: Wait for redirect ────────────────────────────────
        logger.info("Waiting for login redirect…")
        try:
            page.wait_for_url(
                "**/Tips/lenovoIdSuccess.html*",
                timeout=timeout_ms,
            )
        except Exception:
            body_el = page.query_selector("body")
            body_text = body_el.inner_text() if body_el else ""
            for sel in (".error-msg", ".lnv-error", ".alert", "#errorMsg"):
                el = page.query_selector(f"{sel}:visible")
                if el:
                    err = el.text_content() or ""
                    if err.strip():
                        raise RuntimeError(f"Lenovo login failed: {err.strip()}")
            raise RuntimeError(
                f"Lenovo login timed out.  "
                f"URL: {page.url[:200]}  Page: {body_text[:200]}"
            )

        # ── Step 8: Extract WUST token ───────────────────────────────
        current_url = page.url
        parsed = urlparse(current_url)
        params = parse_qs(parsed.query)

        wust_values = params.get("lenovoid.wust", [])
        if wust_values:
            wust = wust_values[0]
        else:
            match = re.search(r"lenovoid\.wust=([^&\"']+)", current_url)
            if match:
                wust = match.group(1)

        # Save cookies for future sessions
        cookies = page.context.cookies()
        _save_cookies(cookies)
        logger.info("Login successful, saved %d cookies", len(cookies))

    if not wust:
        raise RuntimeError("Could not extract WUST token from login redirect")

    logger.info("Obtained WUST token: %s…", wust[:30])
    return wust
